---
title: "Basic Census data"
format: gfm
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(paged.print = FALSE)
```

```{r message=FALSE}
library(tidycensus)
library(tidyverse)
library(tigris)
options(tigris_use_cache = TRUE)
```

```{r}
nm_counties <- counties("NM")
```

# Variables of interest

## 2023

### Place of Birth

```         
Total B05002_001
Native B05002_002
Foreign Born B5002_013
```

### Of Foreign born

```         
Total B05006_001
Europe B05006_002
Asia B05006_047
Eastern Asia B05006_048
China B05006_049
South Central Asia B05006_056
South Eastern Asia B05006_068
Vietnam B05006_007
Western Asia B05006_079
Africa B05006_095
Oceania B05006_130
Latin America B05006_139
Central America B05006_154
Mexico B05006_160
South America B05006_164
Canada B05006_177
```

### Race

These variables include combinations of races

```         
White  B02008_001
Black  B02009_001
NativeAmerican  B02010_001
Asian  B02011_001

Hispanic B03001_003
HispanicMexican B03001_004
HispanicCA B03001_008
```

### Measures

```         
Per capita income (inf adj) B19301_001
Median income B19326_001
Gini B19083_001
```

```{r}
pob_vars = c(
  Native = "B05002_002",
  ForeignBorn = "B05002_013"
)
```

```{r}
native_foreign <- get_acs(
  geography = "county",
  state = "NM",
  variables = pob_vars,
  summary_var = "B05002_001",
  year = 2023,
  cache_table = TRUE,
)
```

```{r}
native_foreign <- native_foreign |> left_join(
  nm_counties,
  by = "GEOID"
)  |> select(GEOID, variable, estimate, moe,
            county = NAME.y, summary_est, 
            geometry)
str(native_foreign)
```

```{r}
ggplot(native_foreign, aes(x = variable, y = estimate, fill = county)) +
  geom_col()
```

```{r}
orig_vars = c(
  Europe = "B05006_002",
  Asia = "B05006_047",
  Eastern_Asia = "B05006_048",
  China = "B05006_049",
  SC_Asia = "B05006_056",
  SE_Asia = "B05006_068",
  Vietnam = "B05006_007",
  Western_Asia = "B05006_079",
  Africa = "B05006_095",
  Oceania = "B05006_130",
  Latin_America = "B05006_139",
  Central_America = "B05006_154",
  Mexico = "B05006_160",
  South_America = "B05006_164",
  Canada = "B05006_177"
)
```

```{r}
foreign_origin <- get_acs(
  geography = "county",
  state = "NM",
  variables = orig_vars,
  summary_var = "B05006_001",
  year = 2023,
  cache_table = TRUE,
)
```

```{r}
foreign_origin <- foreign_origin |> left_join(
  nm_counties,
  by = "GEOID"
)  |> select(GEOID, variable, estimate, moe,
            county = NAME.y, summary_est, 
            geometry)
str(foreign_origin)
```

```{r}
continents <- c(
  "Europe",
  "Central_America",
  "Asia",
  "South_America",
  "Africa",
  "Oceania",
  "Canada"
)
```

```{r fig.height=7}
foreign_origin |> 
  filter(variable %in% continents) |> 
  mutate(variable = fct_reorder(variable, desc(estimate))) |> 
  ggplot(aes(x = variable, y = estimate, fill = county)) +
  geom_col() +
  labs(x = "Continent",
       y = "Population",
       fill = "County",
       title = "Origins of foreign-born New Mexico population",
       subtitle = "By Continent",
       caption = "acs5 2023") +
  scale_y_continuous(labels = scales::comma) +
  theme_gray() +
  theme(axis.text.x = element_text(angle = 30))
```

```{r}
counties_top_8 <- foreign_origin |> 
  group_by(county) |> 
  summarise(est_sum = sum(estimate)) |> 
  slice_max(order_by = est_sum, n = 8) |>
  ungroup()
```

```{r}
counties_top_8
```

```{r}
foreign_origin |> 
  filter(variable %in% continents & county %in% counties_top_8$county) |> 
  mutate(county = fct_reorder(county, desc(summary_est))) |> 
  ggplot(aes(x = county, y = estimate, fill = variable)) +
  geom_col() +
  labs(x = "County",
       y = "Population",
       fill = "Continent",
       title = "Origins of foreign-born New Mexico population",
       subtitle = "Top 10 Counties by Population") +
  scale_y_continuous(labels = scales::comma) +
  scale_fill_viridis_d(labels = c("Africa", "Asia", "Canada", "Central America",
                               "Europe", "Oceania", "South America")) +
  theme_gray() +
  theme(axis.text.x = element_text(angle = 30))
```

```{r}
race_vars = c(
  White = "B02008_001",
  Black = "B02009_001",
  Native_American = "B02010_001",
  Asian = "B02011_001"
)

races <- get_acs(
  geography = "county",
  state = "NM",
  variables = race_vars,
  year = 2023,
  cache_table = TRUE) |> 
  left_join(
    nm_counties,
    by = "GEOID")  |> 
  select(GEOID, variable, estimate, moe,
            county = NAME.y,geometry)
str(races)
```

```{r}
races |> 
  filter(county %in% counties_top_8$county) |> 
  mutate(county = fct_reorder(county, desc(estimate))) |> 
  ggplot(aes(x = county, y = estimate, fill = variable)) +
  geom_col() +
  labs(x = "County",
       y = "Population",
       fill = "Race",
       title = "New Mexico population by race",
       subtitle = "Top 10 Counties by Population",
       caption = "Source: census.gov acs5 2023") +
  scale_y_continuous(labels = scales::comma) +
  scale_fill_viridis_d(labels = c("Asian", "Black",
                                  "Native American", "White")) +
  theme_gray() +
  theme(axis.text.x = element_text(angle = 30))
```

```{r}
hisp_vars = c(
  Non_Hispanic = "B03001_002",
  Hispanic = "B03001_003",
  Hispanic_Mexican  = "B03001_004",
  Hispanic_CA = "B03001_008",
  Hispanic_Spaniard = "B03001_028",
  Hispanic_Spanish = "B03001_029",
  Hispanic_Spanish_American = "B03001_030",
  Hispanic_White = "B03002_013"
)

hispanic <- get_acs(
  geography = "county",
  state = "NM",
  variables = hisp_vars,
  summary_var = "B03001_001",
  year = 2023,
  cache_table = TRUE) |> 
  left_join(nm_counties,
            by = "GEOID") |> 
  select(GEOID, variable, estimate, moe,
            county = NAME.y, summary_est, 
            geometry)
str(hispanic)
head(hispanic)

hispanic_wd <- hispanic |> 
  pivot_wider(names_from = variable, values_from = estimate) 


hisp <- hispanic |> 
  pivot_wider(names_from = variable, values_from = estimate) |> 
  rowwise() |> 
  mutate(Hispanic_Spain = sum(c_across(Hispanic_Spaniard:Hispanic_Spanish_American), na.rm = TRUE)) |> 
  select(-c("Hispanic_Spaniard", "Hispanic_Spanish", "Hispanic_Spanish_American")) |> 
  pivot_longer(cols = Non_Hispanic:Hispanic_Spain, names_to = "variable", values_to = "estimate", values_drop_na = T) |> 
  group_by(county, variable) |> 
  mutate(pop = sum(estimate)) |> 
  distinct(county, variable, .keep_all = TRUE)

hisp
```
```{r}
hisp |> 
  filter(county %in% counties_top_8$county & !(variable %in% c("Hispanic", "Non_Hispanic"))) |> 
  mutate(county = fct_reorder(county, desc(pop))) |> 
  ggplot(aes(x = county, y = pop, fill = factor(variable, levels = c("Hispanic_White", "Hispanic_Mexican", "Hispanic_Spain", "Hispanic_CA")))) +
  geom_col(position = "dodge") +
  labs(x = "County",
       y = "Population",
       fill = "Race",
       title = "Racial Identification of Hispanic Population",
       subtitle = "Top 10 Counties by Population",
       caption = "Source: census.gov acs5 2023") +
  scale_y_continuous(labels = scales::comma) +
  scale_fill_viridis_d(labels = c("White", "Mexicam", "Spanish", "Central American")) +
  theme_gray() +
  theme(axis.text.x = element_text(angle = 30))
```

```{r}
hispanic |> 
  filter(county %in% counties_top_8$county & variable %in% c("Hispanic", "Non_Hispanic")) |> 
  mutate(county = fct_reorder(county, desc(estimate))) |> 
  ggplot(aes(x = county, y = estimate, fill = variable)) +
  geom_col(position = "dodge") +
  labs(x = "County",
       y = "Population",
       fill = "Continent",
       title = "Origins of foreign-born New Mexico population",
       subtitle = "Top 10 Counties by Population") +
  scale_y_continuous(labels = scales::comma) +
  scale_fill_viridis_d() +
  theme_gray() +
  theme(axis.text.x = element_text(angle = 30))
```


```{r}
measure_vars = c(
  PC_Income = "B19301_001",
  Med_Income = "B19326_001",
  Gini = "B19083_001"
)

measures <- get_acs(
  geography = "county",
  state = "NM",
  variables = measure_vars,
  year = 2023,
  cache_table = TRUE,
)
```

```{r eval=FALSE}
Origins |> 
  group_by(GEOID, variable) |> 
  summarise(estimate = sum(estimate), sum_est = summary_est)
```

```{r eval=FALSE}
pop_totals <- Origins |> 
  filter(variable == "Total") |> 
  select(GEOID, Total = estimate)
pop_totals
```

```{r eval=FALSE}
Origins <- Origins |> left_join(
  pop_totals, by = "GEOID"
) |> 
  filter(variable != "Total") |> 
  select(GEOID, county, variable, estimate, 
         summary_est, total=Total, everything())
str(Origins)
```

```{r eval=FALSE}
saveRDS(Origins, "origins.rds")
```

```{r eval=FALSE}
Origins <- Origins |> 
  group_by(county, variable) |> 
  summarise(estimate = sum(estimate),
            foreign = summary_est, total = total) |> 
  mutate(
    pct_of_fb = estimate / foreign,
    pct_of_tot = estimate / total
  ) |> 
  select(-foreign, -total)
Origins
```

```{r eval=FALSE}
Origins |> 
  group_by(variable) |> 
  summarise(
    origin_tot = sum(estimate),
    pct_fb = mean(pct_of_fb),
    pct_tot = mean(pct_of_tot)
  ) |> 
  arrange(desc(origin_tot)) |> 
  ggplot(aes(x = variable, y = origin_tot)) +
  geom_col()
```

```{r eval=FALSE}
Origins |> 
  group_by(county, variable) |> 
  summarise(
    origin_tot = sum(estimate),
    pct_fb = mean(pct_of_fb),
    pct_tot = mean(pct_of_tot)
  ) |> 
  mutate(variable = fct_reorder(variable, desc(origin_tot))) |> 
  ggplot(aes(x = variable, y = origin_tot, fill = county)) +
  geom_col() +
  labs(x = "Country of Origin",
       y = "Population",
       title = "Origins of foreign-born New Mexico population") +
  scale_y_continuous(labels = scales::comma) +
  labs(title)
```

```{r eval=FALSE}
Origin_wide <- Origins |> 
  group_by(county, variable) |> 
  summarise(
    origin_tot = sum(estimate),
    pct_fb = mean(pct_of_fb),
    pct_tot = mean(pct_of_tot)
  ) |> 
  pivot_wider(names_from = variable,
              values_from = c(origin_tot, pct_fb, pct_tot))
```

```{r eval=FALSE}
v23 <- load_variables(2023, "acs5", cache = TRUE)
View(v23)
```
